# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andromeda', '0005_auto_20170515_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andromedausers',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recordatorios',
            name='fechaCreado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
