# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andromeda', '0007_auto_20170521_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andromedausers',
            name='imagen',
            field=models.CharField(default='default.jpg', max_length=50),
        ),
    ]
