# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andromeda', '0009_auto_20170521_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorios',
            name='idAndromedaUser',
            field=models.IntegerField(default='0'),
        ),
    ]
