# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andromeda', '0010_auto_20170521_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorios',
            name='idEstadoRecordatorio',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='recordatorios',
            name='idTipoRecordatorio',
            field=models.IntegerField(default='0'),
        ),
    ]
